### ISSUE TITLE
Better/different default resolution for JakartaMailApiRule

### ISSUE THREAD

**Issue by boris-petrov** [gradlex-org/java-ecosystem-capabilities#11]
Which is the new version of `com.sun.mail:jakarta.mail`... however there's a twist as with everything Jakarta related... :smile: This one package was split it two as far as I understand - `jakarta.mail:jakarta.mail-api` and `org.eclipse.angus:jakarta.mail`... so I'm not sure how `java-ecosystem-capabilities` would handle this.

**Comment by jjohannes** [comment]
Thanks for pointing this out. I checked the Jars. These packages are all interchangeable. They overlap and all have the same Java Module Name - `jakarta.mail` -  (the one given in `module-info.class`). So you basically decide if you want a full package (API+Impl) where you can choose between the `com.sun.mail:jakarta.mail` and the `org.eclipse.angus:jakarta.mail` or just the API - `jakarta.mail:jakarta.mail-api`.

We should include `jakarta.mail:jakarta.mail-api` and `org.eclipse.angus:jakarta.mail` into the JakartaMailApiRule.

**Comment by boris-petrov** [comment]
@jjohannes I think this rule should somehow "prefer" Angus (no matter the version) as that's the "new" thing. Similar to [this](https://github.com/nebula-plugins/gradle-jakartaee-migration-plugin/commit/b0d60abfe183565ba0138d4a92676bf3d26a4d1c). What do you think?

**Comment by boris-petrov** [comment]
@jjohannes you probably missed that too. :smile:

**Comment by jjohannes** [comment]
Thanks. We have to see. I'll adjust the title of this issue.

**Comment by jjohannes** [comment]
Check what the behavior is in 2.0 and either close the issue or clarify what to do for 2.0 or 2.1

**Comment by jjohannes** [comment]
We discussed _default resolution strategies_ again for the "2.0" release. But we circled back to the problem that in cases like this there is no clear default for all situations, because there are alternatives and the user should choose explicitly if they care.

We thought about removing the defaults for some cases (like this one) completely. But that would mean that a user who **does not care** also always will have to make an explicit decision. Also if they are okay if just anything is picked (e.g. because they need the API and do not care about additional unused implementation classes). 
So in the end we decided to keep the "select highest version" default for almost all cases (including this one). Another reason is that figuring out the best default for each cas and keeping discussing them is a maintenance overhead we think is not worth it (and we can't provide at the moment).

Instead, the "2.0" release will provide a DSL which makes it easy to express your own preference. Here, you can then say:

```
jvmDependencyConflicts.conflictResolution {
    select(CapabilityDefinitions.JAKARTA_MAIL_API, "org.eclipse.angus:jakarta.mail")
}
```
