### ISSUE TITLE
Support Guava 32 and newer

### ISSUE THREAD

**Issue by MatanSabag** [gradlex-org/java-ecosystem-capabilities#52]
I saw that there is an explicit if condition `if (majorVersion > 31) return`. 
Is there a reason for that? I don't mind submitting a PR that bumps it to 32, just want to make sure i'm not missing anything else.

**Comment by jjohannes** [comment]
Thank you for bringing this up. We missed the Guava release and definitely want to support it. 

The reason why each release has special handling is that we "merge" the JRE and Android versions to different Variants in one Component. But they have (had?) slightly different dependencies and that needs handling.

Maybe this has improved and it becomes easier for future versions.

It would be great if you provide a PR. It might be a bit involved though. There is a test  - GuavaClasspathTest - that needs to be updated. That test also tests a branch of Guava which I was hoping they would integrate so that the plugin is no longer necessary. But that never happened. If you stumble over that, I can take over that part. Just do the PR as far as you can manage and I can take it from there. Thanks!

**Comment by MatanSabag** [comment]
Thanks Jendrik for your fast response and for improving my PR!
