### ISSUE TITLE
Decide what to do with Guava Rule

### ISSUE THREAD

**Issue by britter** [gradlex-org/java-ecosystem-capabilities#75]
With #81, the `GuavaComponentRule` rule is no longer automatically applied. This rule does everything related to Guava but not related to capabilities:
- For older Versions, it adds the variants that Guava now publishes itself
- For all versions, it removes annotation processor dependencies, however this is a bit opionated

For backward compatibility, we should keep the rule, but no longer register it by default. Instead, document how to add it in the (new) documentation.

**Comment by jjohannes** [comment]
The rule is no longer added by default, because it was quite opinionated about removing transitive dependencies. The  "multi variant" adding is no longer needed for current Guava versions that publish Gradle Metadata.

The "capability" related parts are still present in separate rules (GuavaListenableFutureRule and other related entires in CapabilityDefinitions) .

The original rule will be kept around for users who still need the old behavior. But they need to use it manually. I added a note about that to the documentation in PR #92.
